/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TestsRouteImport } from './routes/tests'
import { Route as SymptomsRouteImport } from './routes/symptoms'
import { Route as RemindersRouteImport } from './routes/reminders'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as HospitalRouteImport } from './routes/hospital'
import { Route as HomeRouteImport } from './routes/home'
import { Route as EmergencyRouteImport } from './routes/emergency'
import { Route as BenefitsRouteImport } from './routes/benefits'
import { Route as AppointmentRouteImport } from './routes/appointment'
import { Route as AnalysisRouteImport } from './routes/analysis'
import { Route as AmbulanceRouteImport } from './routes/ambulance'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ResultModerateRouteImport } from './routes/result.moderate'
import { Route as ResultMildRouteImport } from './routes/result.mild'

const TestsRoute = TestsRouteImport.update({
  id: '/tests',
  path: '/tests',
  getParentRoute: () => rootRouteImport,
} as any)
const SymptomsRoute = SymptomsRouteImport.update({
  id: '/symptoms',
  path: '/symptoms',
  getParentRoute: () => rootRouteImport,
} as any)
const RemindersRoute = RemindersRouteImport.update({
  id: '/reminders',
  path: '/reminders',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const HospitalRoute = HospitalRouteImport.update({
  id: '/hospital',
  path: '/hospital',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const EmergencyRoute = EmergencyRouteImport.update({
  id: '/emergency',
  path: '/emergency',
  getParentRoute: () => rootRouteImport,
} as any)
const BenefitsRoute = BenefitsRouteImport.update({
  id: '/benefits',
  path: '/benefits',
  getParentRoute: () => rootRouteImport,
} as any)
const AppointmentRoute = AppointmentRouteImport.update({
  id: '/appointment',
  path: '/appointment',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalysisRoute = AnalysisRouteImport.update({
  id: '/analysis',
  path: '/analysis',
  getParentRoute: () => rootRouteImport,
} as any)
const AmbulanceRoute = AmbulanceRouteImport.update({
  id: '/ambulance',
  path: '/ambulance',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultModerateRoute = ResultModerateRouteImport.update({
  id: '/result/moderate',
  path: '/result/moderate',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultMildRoute = ResultMildRouteImport.update({
  id: '/result/mild',
  path: '/result/mild',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ambulance': typeof AmbulanceRoute
  '/analysis': typeof AnalysisRoute
  '/appointment': typeof AppointmentRoute
  '/benefits': typeof BenefitsRoute
  '/emergency': typeof EmergencyRoute
  '/home': typeof HomeRoute
  '/hospital': typeof HospitalRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/reminders': typeof RemindersRoute
  '/symptoms': typeof SymptomsRoute
  '/tests': typeof TestsRoute
  '/result/mild': typeof ResultMildRoute
  '/result/moderate': typeof ResultModerateRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ambulance': typeof AmbulanceRoute
  '/analysis': typeof AnalysisRoute
  '/appointment': typeof AppointmentRoute
  '/benefits': typeof BenefitsRoute
  '/emergency': typeof EmergencyRoute
  '/home': typeof HomeRoute
  '/hospital': typeof HospitalRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/reminders': typeof RemindersRoute
  '/symptoms': typeof SymptomsRoute
  '/tests': typeof TestsRoute
  '/result/mild': typeof ResultMildRoute
  '/result/moderate': typeof ResultModerateRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ambulance': typeof AmbulanceRoute
  '/analysis': typeof AnalysisRoute
  '/appointment': typeof AppointmentRoute
  '/benefits': typeof BenefitsRoute
  '/emergency': typeof EmergencyRoute
  '/home': typeof HomeRoute
  '/hospital': typeof HospitalRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/reminders': typeof RemindersRoute
  '/symptoms': typeof SymptomsRoute
  '/tests': typeof TestsRoute
  '/result/mild': typeof ResultMildRoute
  '/result/moderate': typeof ResultModerateRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ambulance'
    | '/analysis'
    | '/appointment'
    | '/benefits'
    | '/emergency'
    | '/home'
    | '/hospital'
    | '/onboarding'
    | '/profile'
    | '/reminders'
    | '/symptoms'
    | '/tests'
    | '/result/mild'
    | '/result/moderate'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ambulance'
    | '/analysis'
    | '/appointment'
    | '/benefits'
    | '/emergency'
    | '/home'
    | '/hospital'
    | '/onboarding'
    | '/profile'
    | '/reminders'
    | '/symptoms'
    | '/tests'
    | '/result/mild'
    | '/result/moderate'
  id:
    | '__root__'
    | '/'
    | '/ambulance'
    | '/analysis'
    | '/appointment'
    | '/benefits'
    | '/emergency'
    | '/home'
    | '/hospital'
    | '/onboarding'
    | '/profile'
    | '/reminders'
    | '/symptoms'
    | '/tests'
    | '/result/mild'
    | '/result/moderate'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AmbulanceRoute: typeof AmbulanceRoute
  AnalysisRoute: typeof AnalysisRoute
  AppointmentRoute: typeof AppointmentRoute
  BenefitsRoute: typeof BenefitsRoute
  EmergencyRoute: typeof EmergencyRoute
  HomeRoute: typeof HomeRoute
  HospitalRoute: typeof HospitalRoute
  OnboardingRoute: typeof OnboardingRoute
  ProfileRoute: typeof ProfileRoute
  RemindersRoute: typeof RemindersRoute
  SymptomsRoute: typeof SymptomsRoute
  TestsRoute: typeof TestsRoute
  ResultMildRoute: typeof ResultMildRoute
  ResultModerateRoute: typeof ResultModerateRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tests': {
      id: '/tests'
      path: '/tests'
      fullPath: '/tests'
      preLoaderRoute: typeof TestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/symptoms': {
      id: '/symptoms'
      path: '/symptoms'
      fullPath: '/symptoms'
      preLoaderRoute: typeof SymptomsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reminders': {
      id: '/reminders'
      path: '/reminders'
      fullPath: '/reminders'
      preLoaderRoute: typeof RemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hospital': {
      id: '/hospital'
      path: '/hospital'
      fullPath: '/hospital'
      preLoaderRoute: typeof HospitalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/emergency': {
      id: '/emergency'
      path: '/emergency'
      fullPath: '/emergency'
      preLoaderRoute: typeof EmergencyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/benefits': {
      id: '/benefits'
      path: '/benefits'
      fullPath: '/benefits'
      preLoaderRoute: typeof BenefitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/appointment': {
      id: '/appointment'
      path: '/appointment'
      fullPath: '/appointment'
      preLoaderRoute: typeof AppointmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analysis': {
      id: '/analysis'
      path: '/analysis'
      fullPath: '/analysis'
      preLoaderRoute: typeof AnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ambulance': {
      id: '/ambulance'
      path: '/ambulance'
      fullPath: '/ambulance'
      preLoaderRoute: typeof AmbulanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/result/moderate': {
      id: '/result/moderate'
      path: '/result/moderate'
      fullPath: '/result/moderate'
      preLoaderRoute: typeof ResultModerateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/result/mild': {
      id: '/result/mild'
      path: '/result/mild'
      fullPath: '/result/mild'
      preLoaderRoute: typeof ResultMildRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AmbulanceRoute: AmbulanceRoute,
  AnalysisRoute: AnalysisRoute,
  AppointmentRoute: AppointmentRoute,
  BenefitsRoute: BenefitsRoute,
  EmergencyRoute: EmergencyRoute,
  HomeRoute: HomeRoute,
  HospitalRoute: HospitalRoute,
  OnboardingRoute: OnboardingRoute,
  ProfileRoute: ProfileRoute,
  RemindersRoute: RemindersRoute,
  SymptomsRoute: SymptomsRoute,
  TestsRoute: TestsRoute,
  ResultMildRoute: ResultMildRoute,
  ResultModerateRoute: ResultModerateRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
